"""
Common types used across Book 2 code examples.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


def _utc_now() -> datetime:
    """Return current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


class PolicyAction(Enum):
    """Actions a policy can take."""
    ALLOW = "allow"
    DENY = "deny"
    RATE_LIMIT = "rate_limit"
    REQUIRE_APPROVAL = "require_approval"
    AUDIT = "audit"


class HealthStatus(Enum):
    """Health status of an agent or service."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


class AlertSeverity(Enum):
    """Severity levels for alerts."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


@dataclass
class AgentIdentity:
    """Identity information for an agent."""
    agent_id: str
    name: str
    organization: str
    roles: List[str]
    permissions: List[str]
    certificate_fingerprint: Optional[str] = None
    created_at: datetime = field(default_factory=_utc_now)
    expires_at: Optional[datetime] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PolicyDecision:
    """Result of a policy evaluation."""
    action: PolicyAction
    policy_id: str
    reason: str
    matched_rules: List[str] = field(default_factory=list)
    conditions: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass
class MetricPoint:
    """A single metric measurement."""
    name: str
    value: float
    timestamp: datetime
    labels: Dict[str, str] = field(default_factory=dict)
    unit: str = ""


@dataclass
class TraceSpan:
    """A span in a distributed trace."""
    trace_id: str
    span_id: str
    parent_span_id: Optional[str]
    operation_name: str
    start_time: datetime
    end_time: Optional[datetime] = None
    status: str = "ok"
    attributes: Dict[str, Any] = field(default_factory=dict)
    events: List[Dict[str, Any]] = field(default_factory=list)


@dataclass
class CostRecord:
    """Record of resource consumption and cost."""
    record_id: str
    agent_id: str
    operation: str
    input_tokens: int = 0
    output_tokens: int = 0
    model: str = ""
    cost_usd: float = 0.0
    timestamp: datetime = field(default_factory=_utc_now)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class AnomalyAlert:
    """Alert generated by anomaly detection."""
    alert_id: str
    detector_type: str
    severity: AlertSeverity
    description: str
    agent_id: Optional[str] = None
    metric_name: Optional[str] = None
    observed_value: Optional[float] = None
    expected_range: Optional[tuple] = None
    timestamp: datetime = field(default_factory=_utc_now)


@dataclass
class EvaluationResult:
    """Result of an agent evaluation."""
    evaluation_id: str
    agent_id: str
    dataset_id: str
    score: float
    passed: bool
    metrics: Dict[str, float] = field(default_factory=dict)
    failures: List[Dict[str, Any]] = field(default_factory=list)
    timestamp: datetime = field(default_factory=_utc_now)
