"""
Chapter 18: Agent Infrastructure and Deployment
==============================================

Implements infrastructure patterns for AI agent deployment:
- Containerized agent deployment
- Kubernetes manifests generation
- Terraform configurations
- Auto-scaling policies
- Health checks and readiness probes

Production-ready deployment patterns for enterprise AI agents.
"""

import json
import yaml
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


class DeploymentTarget(Enum):
    """Supported deployment targets."""
    DOCKER = "docker"
    KUBERNETES = "kubernetes"
    CLOUD_RUN = "cloud_run"
    AWS_ECS = "aws_ecs"
    AZURE_CONTAINER = "azure_container"


class ScalingPolicy(Enum):
    """Auto-scaling policies."""
    CPU_BASED = "cpu"
    MEMORY_BASED = "memory"
    REQUEST_BASED = "request"
    QUEUE_BASED = "queue"
    CUSTOM = "custom"


@dataclass
class ResourceRequirements:
    """Resource requirements for an agent."""
    cpu_request: str = "100m"
    cpu_limit: str = "1000m"
    memory_request: str = "256Mi"
    memory_limit: str = "2Gi"
    gpu_count: int = 0
    gpu_type: str = ""


@dataclass
class HealthCheckConfig:
    """Health check configuration."""
    path: str = "/health"
    port: int = 8080
    initial_delay_seconds: int = 10
    period_seconds: int = 30
    timeout_seconds: int = 5
    failure_threshold: int = 3
    success_threshold: int = 1


@dataclass
class ScalingConfig:
    """Auto-scaling configuration."""
    min_replicas: int = 1
    max_replicas: int = 10
    policy: ScalingPolicy = ScalingPolicy.CPU_BASED
    target_cpu_percent: int = 70
    target_memory_percent: int = 80
    scale_up_stabilization_seconds: int = 60
    scale_down_stabilization_seconds: int = 300
    custom_metrics: list[dict] = field(default_factory=list)


@dataclass
class AgentDeploymentConfig:
    """Complete deployment configuration for an agent."""
    name: str
    image: str
    version: str = "latest"
    replicas: int = 1
    resources: ResourceRequirements = field(default_factory=ResourceRequirements)
    health_check: HealthCheckConfig = field(default_factory=HealthCheckConfig)
    scaling: Optional[ScalingConfig] = None
    environment: dict[str, str] = field(default_factory=dict)
    secrets: list[str] = field(default_factory=list)
    volumes: list[dict] = field(default_factory=list)
    labels: dict[str, str] = field(default_factory=dict)
    annotations: dict[str, str] = field(default_factory=dict)
    service_port: int = 8080
    namespace: str = "default"


class DockerfileGenerator:
    """
    Generates Dockerfiles for agent deployment.
    """

    @staticmethod
    def generate(config: AgentDeploymentConfig,
                 base_image: str = "python:3.11-slim",
                 additional_deps: Optional[list[str]] = None) -> str:
        """Generate a Dockerfile for the agent."""
        deps = additional_deps or []

        dockerfile = f"""# Agent Dockerfile - {config.name}
# Auto-generated by agent infrastructure toolkit

FROM {base_image}

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    curl \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
"""

        if deps:
            dockerfile += f"""
# Install additional dependencies
RUN pip install --no-cache-dir {' '.join(deps)}
"""

        dockerfile += f"""
# Copy application code
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1
ENV AGENT_NAME={config.name}
ENV PORT={config.service_port}

# Health check
HEALTHCHECK --interval={config.health_check.period_seconds}s \\
    --timeout={config.health_check.timeout_seconds}s \\
    --start-period={config.health_check.initial_delay_seconds}s \\
    --retries={config.health_check.failure_threshold} \\
    CMD curl -f http://localhost:{config.health_check.port}{config.health_check.path} || exit 1

# Expose port
EXPOSE {config.service_port}

# Run the agent
CMD ["python", "-m", "agent.main"]
"""
        return dockerfile


class KubernetesManifestGenerator:
    """
    Generates Kubernetes manifests for agent deployment.
    """

    @staticmethod
    def generate_deployment(config: AgentDeploymentConfig) -> dict:
        """Generate Kubernetes Deployment manifest."""
        deployment = {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "metadata": {
                "name": config.name,
                "namespace": config.namespace,
                "labels": {
                    "app": config.name,
                    "version": config.version,
                    **config.labels
                },
                "annotations": config.annotations
            },
            "spec": {
                "replicas": config.replicas,
                "selector": {
                    "matchLabels": {
                        "app": config.name
                    }
                },
                "template": {
                    "metadata": {
                        "labels": {
                            "app": config.name,
                            "version": config.version
                        }
                    },
                    "spec": {
                        "containers": [{
                            "name": config.name,
                            "image": f"{config.image}:{config.version}",
                            "ports": [{
                                "containerPort": config.service_port,
                                "name": "http"
                            }],
                            "resources": {
                                "requests": {
                                    "cpu": config.resources.cpu_request,
                                    "memory": config.resources.memory_request
                                },
                                "limits": {
                                    "cpu": config.resources.cpu_limit,
                                    "memory": config.resources.memory_limit
                                }
                            },
                            "livenessProbe": {
                                "httpGet": {
                                    "path": config.health_check.path,
                                    "port": config.health_check.port
                                },
                                "initialDelaySeconds": config.health_check.initial_delay_seconds,
                                "periodSeconds": config.health_check.period_seconds,
                                "timeoutSeconds": config.health_check.timeout_seconds,
                                "failureThreshold": config.health_check.failure_threshold
                            },
                            "readinessProbe": {
                                "httpGet": {
                                    "path": f"{config.health_check.path}/ready",
                                    "port": config.health_check.port
                                },
                                "initialDelaySeconds": 5,
                                "periodSeconds": 10
                            },
                            "env": [
                                {"name": k, "value": v}
                                for k, v in config.environment.items()
                            ]
                        }]
                    }
                }
            }
        }

        # Add GPU resources if needed
        if config.resources.gpu_count > 0:
            deployment["spec"]["template"]["spec"]["containers"][0]["resources"]["limits"]["nvidia.com/gpu"] = config.resources.gpu_count

        # Add secrets
        if config.secrets:
            deployment["spec"]["template"]["spec"]["containers"][0]["envFrom"] = [
                {"secretRef": {"name": secret}} for secret in config.secrets
            ]

        # Add volumes
        if config.volumes:
            deployment["spec"]["template"]["spec"]["volumes"] = config.volumes
            deployment["spec"]["template"]["spec"]["containers"][0]["volumeMounts"] = [
                {"name": v["name"], "mountPath": v.get("mountPath", f"/mnt/{v['name']}")}
                for v in config.volumes
            ]

        return deployment

    @staticmethod
    def generate_service(config: AgentDeploymentConfig) -> dict:
        """Generate Kubernetes Service manifest."""
        return {
            "apiVersion": "v1",
            "kind": "Service",
            "metadata": {
                "name": config.name,
                "namespace": config.namespace,
                "labels": {
                    "app": config.name
                }
            },
            "spec": {
                "type": "ClusterIP",
                "ports": [{
                    "port": config.service_port,
                    "targetPort": config.service_port,
                    "protocol": "TCP",
                    "name": "http"
                }],
                "selector": {
                    "app": config.name
                }
            }
        }

    @staticmethod
    def generate_hpa(config: AgentDeploymentConfig) -> Optional[dict]:
        """Generate Horizontal Pod Autoscaler manifest."""
        if not config.scaling:
            return None

        hpa = {
            "apiVersion": "autoscaling/v2",
            "kind": "HorizontalPodAutoscaler",
            "metadata": {
                "name": f"{config.name}-hpa",
                "namespace": config.namespace
            },
            "spec": {
                "scaleTargetRef": {
                    "apiVersion": "apps/v1",
                    "kind": "Deployment",
                    "name": config.name
                },
                "minReplicas": config.scaling.min_replicas,
                "maxReplicas": config.scaling.max_replicas,
                "metrics": [],
                "behavior": {
                    "scaleUp": {
                        "stabilizationWindowSeconds": config.scaling.scale_up_stabilization_seconds
                    },
                    "scaleDown": {
                        "stabilizationWindowSeconds": config.scaling.scale_down_stabilization_seconds
                    }
                }
            }
        }

        # Add metrics based on policy
        if config.scaling.policy == ScalingPolicy.CPU_BASED:
            hpa["spec"]["metrics"].append({
                "type": "Resource",
                "resource": {
                    "name": "cpu",
                    "target": {
                        "type": "Utilization",
                        "averageUtilization": config.scaling.target_cpu_percent
                    }
                }
            })

        if config.scaling.policy == ScalingPolicy.MEMORY_BASED:
            hpa["spec"]["metrics"].append({
                "type": "Resource",
                "resource": {
                    "name": "memory",
                    "target": {
                        "type": "Utilization",
                        "averageUtilization": config.scaling.target_memory_percent
                    }
                }
            })

        # Add custom metrics
        for custom in config.scaling.custom_metrics:
            hpa["spec"]["metrics"].append(custom)

        return hpa

    @staticmethod
    def generate_configmap(config: AgentDeploymentConfig,
                           data: dict) -> dict:
        """Generate ConfigMap manifest."""
        return {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {
                "name": f"{config.name}-config",
                "namespace": config.namespace
            },
            "data": {k: str(v) for k, v in data.items()}
        }

    @staticmethod
    def generate_all(config: AgentDeploymentConfig) -> str:
        """Generate all Kubernetes manifests as YAML."""
        manifests = []

        manifests.append(KubernetesManifestGenerator.generate_deployment(config))
        manifests.append(KubernetesManifestGenerator.generate_service(config))

        if config.scaling:
            hpa = KubernetesManifestGenerator.generate_hpa(config)
            if hpa:
                manifests.append(hpa)

        return "\n---\n".join(yaml.dump(m, default_flow_style=False) for m in manifests)


class TerraformGenerator:
    """
    Generates Terraform configurations for agent infrastructure.
    """

    @staticmethod
    def generate_gcp_cloud_run(config: AgentDeploymentConfig) -> str:
        """Generate Terraform for GCP Cloud Run deployment."""
        return f'''# Terraform configuration for {config.name}
# GCP Cloud Run deployment

terraform {{
  required_providers {{
    google = {{
      source  = "hashicorp/google"
      version = "~> 4.0"
    }}
  }}
}}

variable "project_id" {{
  description = "GCP Project ID"
  type        = string
}}

variable "region" {{
  description = "GCP Region"
  type        = string
  default     = "us-central1"
}}

resource "google_cloud_run_service" "{config.name.replace("-", "_")}" {{
  name     = "{config.name}"
  location = var.region

  template {{
    spec {{
      containers {{
        image = "{config.image}:{config.version}"

        ports {{
          container_port = {config.service_port}
        }}

        resources {{
          limits = {{
            cpu    = "{config.resources.cpu_limit}"
            memory = "{config.resources.memory_limit}"
          }}
        }}

        {TerraformGenerator._generate_env_vars(config.environment)}

        startup_probe {{
          http_get {{
            path = "{config.health_check.path}"
            port = {config.health_check.port}
          }}
          initial_delay_seconds = {config.health_check.initial_delay_seconds}
          period_seconds        = {config.health_check.period_seconds}
          failure_threshold     = {config.health_check.failure_threshold}
        }}

        liveness_probe {{
          http_get {{
            path = "{config.health_check.path}"
            port = {config.health_check.port}
          }}
          period_seconds    = {config.health_check.period_seconds}
          failure_threshold = {config.health_check.failure_threshold}
        }}
      }}

      container_concurrency = 80
      timeout_seconds       = 300
    }}

    metadata {{
      annotations = {{
        "autoscaling.knative.dev/minScale" = "{config.scaling.min_replicas if config.scaling else 1}"
        "autoscaling.knative.dev/maxScale" = "{config.scaling.max_replicas if config.scaling else 10}"
      }}
    }}
  }}

  traffic {{
    percent         = 100
    latest_revision = true
  }}
}}

# IAM policy to allow unauthenticated access (adjust as needed)
resource "google_cloud_run_service_iam_member" "{config.name.replace("-", "_")}_invoker" {{
  location = google_cloud_run_service.{config.name.replace("-", "_")}.location
  service  = google_cloud_run_service.{config.name.replace("-", "_")}.name
  role     = "roles/run.invoker"
  member   = "allUsers"
}}

output "service_url" {{
  value = google_cloud_run_service.{config.name.replace("-", "_")}.status[0].url
}}
'''

    @staticmethod
    def _generate_env_vars(env: dict) -> str:
        if not env:
            return ""

        lines = []
        for k, v in env.items():
            lines.append(f'''
        env {{
          name  = "{k}"
          value = "{v}"
        }}''')
        return "\n".join(lines)

    @staticmethod
    def generate_aws_ecs(config: AgentDeploymentConfig) -> str:
        """Generate Terraform for AWS ECS Fargate deployment."""
        return f'''# Terraform configuration for {config.name}
# AWS ECS Fargate deployment

terraform {{
  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }}
  }}
}}

variable "region" {{
  description = "AWS Region"
  type        = string
  default     = "us-east-1"
}}

variable "vpc_id" {{
  description = "VPC ID"
  type        = string
}}

variable "subnet_ids" {{
  description = "Subnet IDs for ECS tasks"
  type        = list(string)
}}

# ECS Cluster
resource "aws_ecs_cluster" "{config.name.replace("-", "_")}_cluster" {{
  name = "{config.name}-cluster"

  setting {{
    name  = "containerInsights"
    value = "enabled"
  }}
}}

# Task Definition
resource "aws_ecs_task_definition" "{config.name.replace("-", "_")}" {{
  family                   = "{config.name}"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = {TerraformGenerator._cpu_to_aws(config.resources.cpu_limit)}
  memory                   = {TerraformGenerator._memory_to_aws(config.resources.memory_limit)}
  execution_role_arn       = aws_iam_role.ecs_execution_role.arn
  task_role_arn            = aws_iam_role.ecs_task_role.arn

  container_definitions = jsonencode([
    {{
      name      = "{config.name}"
      image     = "{config.image}:{config.version}"
      essential = true

      portMappings = [
        {{
          containerPort = {config.service_port}
          hostPort      = {config.service_port}
          protocol      = "tcp"
        }}
      ]

      healthCheck = {{
        command     = ["CMD-SHELL", "curl -f http://localhost:{config.health_check.port}{config.health_check.path} || exit 1"]
        interval    = {config.health_check.period_seconds}
        timeout     = {config.health_check.timeout_seconds}
        retries     = {config.health_check.failure_threshold}
        startPeriod = {config.health_check.initial_delay_seconds}
      }}

      logConfiguration = {{
        logDriver = "awslogs"
        options = {{
          "awslogs-group"         = "/ecs/{config.name}"
          "awslogs-region"        = var.region
          "awslogs-stream-prefix" = "ecs"
        }}
      }}

      environment = [
        {TerraformGenerator._env_to_aws_format(config.environment)}
      ]
    }}
  ])
}}

# ECS Service
resource "aws_ecs_service" "{config.name.replace("-", "_")}" {{
  name            = "{config.name}"
  cluster         = aws_ecs_cluster.{config.name.replace("-", "_")}_cluster.id
  task_definition = aws_ecs_task_definition.{config.name.replace("-", "_")}.arn
  desired_count   = {config.replicas}
  launch_type     = "FARGATE"

  network_configuration {{
    subnets          = var.subnet_ids
    security_groups  = [aws_security_group.{config.name.replace("-", "_")}_sg.id]
    assign_public_ip = true
  }}
}}

# Security Group
resource "aws_security_group" "{config.name.replace("-", "_")}_sg" {{
  name        = "{config.name}-sg"
  description = "Security group for {config.name}"
  vpc_id      = var.vpc_id

  ingress {{
    from_port   = {config.service_port}
    to_port     = {config.service_port}
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }}

  egress {{
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }}
}}

# IAM Roles (simplified)
resource "aws_iam_role" "ecs_execution_role" {{
  name = "{config.name}-execution-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {{
          Service = "ecs-tasks.amazonaws.com"
        }}
      }}
    ]
  }})
}}

resource "aws_iam_role" "ecs_task_role" {{
  name = "{config.name}-task-role"

  assume_role_policy = jsonencode({{
    Version = "2012-10-17"
    Statement = [
      {{
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {{
          Service = "ecs-tasks.amazonaws.com"
        }}
      }}
    ]
  }})
}}

resource "aws_iam_role_policy_attachment" "ecs_execution_role_policy" {{
  role       = aws_iam_role.ecs_execution_role.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
}}

# CloudWatch Log Group
resource "aws_cloudwatch_log_group" "{config.name.replace("-", "_")}_logs" {{
  name              = "/ecs/{config.name}"
  retention_in_days = 30
}}
'''

    @staticmethod
    def _cpu_to_aws(cpu: str) -> int:
        """Convert Kubernetes CPU to AWS Fargate CPU units."""
        if cpu.endswith("m"):
            millicores = int(cpu[:-1])
            return max(256, min(4096, (millicores // 256) * 256))
        return 256

    @staticmethod
    def _memory_to_aws(memory: str) -> int:
        """Convert Kubernetes memory to AWS Fargate memory."""
        if memory.endswith("Gi"):
            return int(memory[:-2]) * 1024
        elif memory.endswith("Mi"):
            return int(memory[:-2])
        return 512

    @staticmethod
    def _env_to_aws_format(env: dict) -> str:
        if not env:
            return ""

        items = [f'{{"name": "{k}", "value": "{v}"}}' for k, v in env.items()]
        return ",\n        ".join(items)


class InfrastructureGenerator:
    """
    Main class for generating all infrastructure artifacts.
    """

    def __init__(self, config: AgentDeploymentConfig):
        self.config = config

    def generate_dockerfile(self, **kwargs) -> str:
        """Generate Dockerfile."""
        return DockerfileGenerator.generate(self.config, **kwargs)

    def generate_kubernetes(self) -> str:
        """Generate Kubernetes manifests."""
        return KubernetesManifestGenerator.generate_all(self.config)

    def generate_terraform_gcp(self) -> str:
        """Generate Terraform for GCP."""
        return TerraformGenerator.generate_gcp_cloud_run(self.config)

    def generate_terraform_aws(self) -> str:
        """Generate Terraform for AWS."""
        return TerraformGenerator.generate_aws_ecs(self.config)

    def generate_all(self, output_dir: str = ".") -> dict:
        """Generate all infrastructure files."""
        files = {
            f"{output_dir}/Dockerfile": self.generate_dockerfile(),
            f"{output_dir}/kubernetes/manifests.yaml": self.generate_kubernetes(),
            f"{output_dir}/terraform/gcp/main.tf": self.generate_terraform_gcp(),
            f"{output_dir}/terraform/aws/main.tf": self.generate_terraform_aws()
        }
        return files


# =============================================================================
# Example Usage
# =============================================================================

def main():
    """Demonstration of infrastructure generation."""
    print("=" * 60)
    print("Agent Infrastructure Generation")
    print("=" * 60)

    # Create deployment configuration
    config = AgentDeploymentConfig(
        name="research-agent",
        image="myregistry/research-agent",
        version="1.2.0",
        replicas=3,
        resources=ResourceRequirements(
            cpu_request="500m",
            cpu_limit="2000m",
            memory_request="1Gi",
            memory_limit="4Gi"
        ),
        health_check=HealthCheckConfig(
            path="/health",
            port=8080,
            initial_delay_seconds=30,
            period_seconds=10
        ),
        scaling=ScalingConfig(
            min_replicas=2,
            max_replicas=20,
            policy=ScalingPolicy.CPU_BASED,
            target_cpu_percent=60
        ),
        environment={
            "MODEL_PROVIDER": "anthropic",
            "LOG_LEVEL": "info",
            "MAX_TOKENS": "4096"
        },
        secrets=["api-keys", "database-credentials"],
        namespace="agents",
        labels={
            "team": "ai-platform",
            "env": "production"
        }
    )

    generator = InfrastructureGenerator(config)

    # Generate Dockerfile
    print("\n" + "-" * 40)
    print("Dockerfile")
    print("-" * 40)
    dockerfile = generator.generate_dockerfile()
    print(dockerfile[:500] + "...")

    # Generate Kubernetes manifests
    print("\n" + "-" * 40)
    print("Kubernetes Manifests")
    print("-" * 40)
    k8s = generator.generate_kubernetes()
    print(k8s[:1000] + "...")

    # Generate Terraform (GCP)
    print("\n" + "-" * 40)
    print("Terraform (GCP Cloud Run)")
    print("-" * 40)
    tf_gcp = generator.generate_terraform_gcp()
    print(tf_gcp[:1000] + "...")

    # Generate Terraform (AWS)
    print("\n" + "-" * 40)
    print("Terraform (AWS ECS)")
    print("-" * 40)
    tf_aws = generator.generate_terraform_aws()
    print(tf_aws[:1000] + "...")

    # Summary
    print("\n" + "=" * 60)
    print("Infrastructure Generation Summary")
    print("=" * 60)
    print(f"\nAgent: {config.name}")
    print(f"Image: {config.image}:{config.version}")
    print(f"Replicas: {config.replicas}")
    print(f"Resources: CPU {config.resources.cpu_request}-{config.resources.cpu_limit}, "
          f"Memory {config.resources.memory_request}-{config.resources.memory_limit}")
    print(f"Scaling: {config.scaling.min_replicas}-{config.scaling.max_replicas} replicas")
    print(f"\nGenerated files:")
    print("  - Dockerfile")
    print("  - kubernetes/manifests.yaml (Deployment, Service, HPA)")
    print("  - terraform/gcp/main.tf (Cloud Run)")
    print("  - terraform/aws/main.tf (ECS Fargate)")


if __name__ == "__main__":
    main()
